"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-36@x*o7yus6n7@i5e38smp1+q)o(kx=utr681l*v=zcjmp!6w1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio_app', # Add this line to the list of installed apps
]

JAZZMIN_SETTINGS = {
    # Title of the window (defaults to current_admin_site.site_title if absent)
    "site_title": "MyPortfolio Admin",
    # Title on the login screen and brand (19 chars max)
    "site_header": "MyPortfolio",
    "site_brand": "MyPortfolio",
    # Welcome text on the login screen
    "welcome_sign": "Welcome to MyPortfolio Admin",
    # Copyright text in the footer
  
    # Optional: Add a logo (place it in your static files, e.g., static/images/logo.png)
    "site_logo": "images/logo.png",
    # Enable language chooser (if you use internationalization)
    "language_chooser": False,
    # Show the sidebar
    "show_sidebar": True,
    # Auto-expand the navigation menu
    "navigation_expanded": True,
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "theme": "cyborg",  # Options: flatly, cerulean, cyborg, darkly, etc.
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['portfolio_app/templates'], # Add this line to the list of template directories
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Use PostgreSQL engine
        'NAME': 'myportfolio',                   # Database name
        'USER': 'postgres',                 # PostgreSQL user
        'PASSWORD': 'rosan',                  # User password
        'HOST': 'localhost',                        # Host (localhost for local setup)
        'PORT': '5432',                             # Default PostgreSQL port
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Path to the 'static' directory in your project
]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field


"""
TWILIO_ACCOUNT_SID = 'AC2e001aca9af31cef248d6e51b3b12791'
TWILIO_AUTH_TOKEN = '4e844366149e084092193b90e5de167a'
TWILIO_PHONE_NUMBER = '+18312499917'
ADMIN_PHONE_NUMBER = '+9779814578091' """


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'rosanranamagar34@gmail.com'  # Your Gmail sender address
EMAIL_HOST_PASSWORD = 'joja rmad yxeb kjwa'  # App Password if 2FA is enabled
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER